name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Parse .tool-versions
        uses: wistia/parse-tool-versions@v2.1.1

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY }}

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest -v
